# Generated by Django 4.2.17 on 2024-12-06 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliateincentive',
            name='affiliate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_incentive_affiliate', to='affiliate.affiliate'),
        ),
        migrations.AlterField(
            model_name='affiliateincentive',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_incentive_program', to='affiliate.affiliateprogram'),
        ),
    ]
