# Generated by Django 5.1.3 on 2024-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
