# Generated by Django 5.1.3 on 2024-11-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_referralcode_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referral.referralprogram'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralprogrampartecipation',
            name='programs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_program_partecipation_programs', to='referral.referralprogram'),
        ),
        migrations.AlterField(
            model_name='referralprogrampartecipation',
            name='referral_codes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_program_partecipation_referral_codes', to='referral.referralcode'),
        ),
    ]
