# Generated by Django 5.1.3 on 2024-11-28 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_alter_referral_program'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ManyToManyField(related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
