# Generated by Django 5.1.3 on 2024-11-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0007_remove_referral_referred_referral_referred'),
    ]

    operations = [
    ]
