# Generated by Django 5.1.3 on 2024-11-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0008_auto_20241129_2048'),
    ]

    operations = [
    ]
