# Generated by Django 5.1.3 on 2024-11-30 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_alter_referral_referred_alter_referral_referrer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred',
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.ManyToManyField(related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
