# Generated by Django 5.1.3 on 2024-12-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='transactions',
            field=models.ManyToManyField(related_name='txns', to='referral.referraltransaction'),
        ),
    ]
